### ISSUE TITLE
Allow `playwright test` CLI arguments to be passed

### ISSUE THREAD

**Issue by d-koppenhagen** [playwright-community/playwright-ng-schematics#3]
Currently the schematic will setup the `e2e` command for angular using the `playwright-ng-schematics:playwright` builder.
It works as expected when executing `ng e2e`.
However, sometimes you'll need to pass CLI arguments (such as `--ui` or `--debug` or `--trace on`) - see list when executing ` npx playwright test --help`.
I would expect to bypass the arguments from `ng e2e` through `playwright test`.

e.g.

```bash
ng e2e --ui
```

should become:

```bash
npx playwright test --ui
```

**Comment by jfgreffier** [comment]
It seems that it is not possible to pass arbitrary option via `ng e2e`, even if the option schema allows it.

So I've added the options for debug, trace, u (update-snapshot), ui. You can just use playwright test directly, I've added mention of this in the docs.

It's available in 1.0.1 let me know if this works for you

**Comment by d-koppenhagen** [comment]
okay, it's fine I think :)
